/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resumes: Resume;
    leads: Lead;
    categories: Category;
    posts: Post;
    jobs: Job;
    'job-applications': JobApplication;
    'case-studies': CaseStudy;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resumes: ResumesSelect<false> | ResumesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes".
 */
export interface Resume {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  fullName?: string | null;
  email: string;
  company?: string | null;
  role?: string | null;
  budget?: string | null;
  area?: string | null;
  message?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  category: string | Category;
  featuredImage: string | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Choose how to write content — Rich Text editor or raw HTML
   */
  contentMode?: ('richText' | 'html') | null;
  /**
   * Paste your HTML content here
   */
  contentHTML?: string | null;
  publishDate: string;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  title: string;
  slug?: string | null;
  location?: string | null;
  type?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
  mode?: ('remote' | 'hybrid' | 'on-site') | null;
  department?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('open' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  linkedinProfile?: string | null;
  message?: string | null;
  resume: string | Resume;
  job?: (string | null) | Job;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  /**
   * Project name (e.g. "Paper Trail")
   */
  title: string;
  /**
   * Auto-generated from title
   */
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Client name (e.g. "Java Paper Group")
   */
  client: string;
  /**
   * Industry label (e.g. "Consumer Tech & E-Commerce")
   */
  industry: string;
  /**
   * Short subtitle shown on detail page
   */
  tagline?: string | null;
  /**
   * Card image shown on the listing page
   */
  coverImage: string | Media;
  /**
   * App screenshot / hero image at the top of the detail page
   */
  heroImage?: (string | null) | Media;
  /**
   * Short description of the client shown in the info block
   */
  clientDescription?: string | null;
  /**
   * Paragraph describing the business challenge
   */
  challenge?: string | null;
  /**
   * Solutions delivered — use bullet list in the editor
   */
  solutions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Product / dashboard screenshots shown in the gallery
   */
  screenshots?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Measurable outcomes — use bullet list in the editor
   */
  impact?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Service name (e.g. "AI Consulting Services")
   */
  title: string;
  /**
   * Auto-generated from title
   */
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Highlighted subtitle (e.g. "Find out where AI makes sense...")
   */
  tagline?: string | null;
  /**
   * CSS hex color for tagline text. Default: #E05C00
   */
  taglineColor?: string | null;
  /**
   * Brief description shown on the listing card and hero
   */
  shortDescription?: string | null;
  /**
   * Additional paragraph below the description in the hero
   */
  heroDetail?: string | null;
  /**
   * CTA button label
   */
  ctaText?: string | null;
  /**
   * CTA button URL
   */
  ctaLink?: string | null;
  /**
   * Image shown on the services listing card and detail page
   */
  coverImage?: (string | null) | Media;
  /**
   * Feature cards shown in the grid below the hero
   */
  benefits?:
    | {
        /**
         * SVG or PNG icon
         */
        iconImage?: (string | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed service overview — shown as a content section
   */
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Section heading (e.g. "Challenges in AI Adoption")
   */
  challengesSectionTitle?: string | null;
  /**
   * Each row = visible problem (left) + hidden problem (right)
   */
  challengeRows?:
    | {
        /**
         * Left column — the problem the client can see
         */
        visibleProblem: string;
        /**
         * Right column — the underlying / hidden problem
         */
        hiddenProblem: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Closing statement below the challenges table
   */
  challengesConclusion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Small bracket label above the title (e.g. "HOW WE APPROACH AI CONSULTING")
   */
  thinkingModelLabel?: string | null;
  /**
   * Section heading (e.g. "Towards a Solution: Our Thinking Model")
   */
  thinkingModelTitle?: string | null;
  /**
   * Subtitle paragraph below the section heading
   */
  thinkingModelDescription?: string | null;
  /**
   * Principle cards shown in the 4-column grid
   */
  thinkingModelPrinciples?:
    | {
        /**
         * Illustration / icon for this principle
         */
        icon?: (string | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * White heading (e.g. "Find Out Where AI Actually Delivers")
   */
  midCtaTitle?: string | null;
  /**
   * Orange line below the title (e.g. "Measurable Value.")
   */
  midCtaHighlight?: string | null;
  /**
   * CTA button label
   */
  midCtaButtonText?: string | null;
  /**
   * CTA button URL
   */
  midCtaButtonLink?: string | null;
  /**
   * e.g. "What Makes Our AI Consultation Unique?"
   */
  uniqueSectionTitle?: string | null;
  /**
   * Cards for the 4-col unique grid
   */
  uniqueSectionItems?:
    | {
        icon?: (string | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Traditional Approach vs NeXus Approach"
   */
  comparisonTitle?: string | null;
  /**
   * Left column header (e.g. "Traditional IT Consulting")
   */
  comparisonLeftLabel?: string | null;
  /**
   * Right column header (e.g. "NeXus AI Consulting")
   */
  comparisonRightLabel?: string | null;
  /**
   * Left column items (traditional / negative)
   */
  comparisonLeftItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Right column items (NeXus / positive)
   */
  comparisonRightItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Step-by-Step Service Delivery"
   */
  processSectionTitle?: string | null;
  /**
   * Subtitle below the heading
   */
  processSectionSubtitle?: string | null;
  /**
   * Phase cards — auto-numbered PHASE 01, 02...
   */
  processSteps?:
    | {
        icon?: (string | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * White text before first highlight (e.g. "Want To Know Which")
   */
  processCtaTitlePart1?: string | null;
  /**
   * First orange inline word(s) (e.g. "Ai Investments")
   */
  processCtaHighlight1?: string | null;
  /**
   * White text between highlights (e.g. "Deliver The")
   */
  processCtaTitlePart2?: string | null;
  /**
   * Second orange inline word(s) (e.g. "Highest Roi")
   */
  processCtaHighlight2?: string | null;
  /**
   * White text after second highlight (e.g. "In Your Industry?")
   */
  processCtaTitlePart3?: string | null;
  /**
   * CTA button label
   */
  processCtaButtonText?: string | null;
  /**
   * CTA button URL
   */
  processCtaButtonLink?: string | null;
  /**
   * Deliverables / outcomes the client receives
   */
  whatWeDeliver?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Plain heading text (e.g. "Business Impact")
   */
  timelineSectionTitle?: string | null;
  /**
   * Orange highlighted word(s) after title (e.g. "Over Time")
   */
  timelineSectionHighlight?: string | null;
  /**
   * Timeline cards — auto-numbered. Description shows on hover.
   */
  timelineItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Impact Stories: Real Stories of AI Transformation"
   */
  impactStoriesSectionTitle?: string | null;
  /**
   * Short intro paragraph below the section title
   */
  impactStoriesSectionDescription?: string | null;
  /**
   * Each item = one story card
   */
  impactStories?:
    | {
        /**
         * e.g. "₹22L/Month From One Week of Analysis"
         */
        headline: string;
        description?: string | null;
        /**
         * Optional image shown instead of the chart (e.g. screenshot, graph photo)
         */
        image?: (string | null) | Media;
        /**
         * Label shown on chart, e.g. "+120% ROI"
         */
        chartLabel?: string | null;
        /**
         * e.g. "What we discovered during our AI consulting audit:"
         */
        discoveryTitle?: string | null;
        discoveryIntro?: string | null;
        discoveryPoints?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        actionLabel?: string | null;
        actionText?: string | null;
        impactLabel?: string | null;
        impactText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section heading (e.g. "Who AI Consulting Is For")
   */
  audienceSectionTitle?: string | null;
  /**
   * Carousel cards — each has an image, title, and description.
   */
  audienceItems?:
    | {
        title: string;
        description?: string | null;
        /**
         * Card image (recommended 4:3 ratio)
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Plain text before highlight (e.g. "Get an")
   */
  ctaBannerTitle?: string | null;
  /**
   * Orange highlighted words (e.g. "AI Feasibility")
   */
  ctaBannerHighlight?: string | null;
  /**
   * Text after highlight (e.g. "Assessment")
   */
  ctaBannerTitleSuffix?: string | null;
  ctaBannerDescription?: string | null;
  ctaBannerButtonText?: string | null;
  ctaBannerButtonLink?: string | null;
  /**
   * e.g. "Frequently Asked Questions"
   */
  faqSectionTitle?: string | null;
  /**
   * Each item = one question + answer
   */
  faqItems?:
    | {
        question: string;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Left sticky heading (e.g. "What We Deliver")
   */
  deliverablesSectionTitle?: string | null;
  /**
   * Orange subtitle below heading (e.g. "(And Why Each Deliverable Exists)")
   */
  deliverablesSectionSubtitle?: string | null;
  /**
   * Each card = one deliverable with impact + risk
   */
  deliverables?:
    | {
        title: string;
        description?: string | null;
        /**
         * Why It Exists text
         */
        whyItExists?: string | null;
        /**
         * Business Impact text
         */
        businessImpact?: string | null;
        /**
         * Risk Mitigation text
         */
        riskMitigation?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'resumes';
        value: string | Resume;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: string | JobApplication;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes_select".
 */
export interface ResumesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  company?: T;
  role?: T;
  budget?: T;
  area?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  contentMode?: T;
  contentHTML?: T;
  publishDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  type?: T;
  mode?: T;
  department?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  linkedinProfile?: T;
  message?: T;
  resume?: T;
  job?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  order?: T;
  client?: T;
  industry?: T;
  tagline?: T;
  coverImage?: T;
  heroImage?: T;
  clientDescription?: T;
  challenge?: T;
  solutions?: T;
  screenshots?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  impact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  order?: T;
  tagline?: T;
  taglineColor?: T;
  shortDescription?: T;
  heroDetail?: T;
  ctaText?: T;
  ctaLink?: T;
  coverImage?: T;
  benefits?:
    | T
    | {
        iconImage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  overview?: T;
  challengesSectionTitle?: T;
  challengeRows?:
    | T
    | {
        visibleProblem?: T;
        hiddenProblem?: T;
        id?: T;
      };
  challengesConclusion?: T;
  thinkingModelLabel?: T;
  thinkingModelTitle?: T;
  thinkingModelDescription?: T;
  thinkingModelPrinciples?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  midCtaTitle?: T;
  midCtaHighlight?: T;
  midCtaButtonText?: T;
  midCtaButtonLink?: T;
  uniqueSectionTitle?: T;
  uniqueSectionItems?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  comparisonTitle?: T;
  comparisonLeftLabel?: T;
  comparisonRightLabel?: T;
  comparisonLeftItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  comparisonRightItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  processSectionTitle?: T;
  processSectionSubtitle?: T;
  processSteps?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  processCtaTitlePart1?: T;
  processCtaHighlight1?: T;
  processCtaTitlePart2?: T;
  processCtaHighlight2?: T;
  processCtaTitlePart3?: T;
  processCtaButtonText?: T;
  processCtaButtonLink?: T;
  whatWeDeliver?: T;
  timelineSectionTitle?: T;
  timelineSectionHighlight?: T;
  timelineItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  impactStoriesSectionTitle?: T;
  impactStoriesSectionDescription?: T;
  impactStories?:
    | T
    | {
        headline?: T;
        description?: T;
        image?: T;
        chartLabel?: T;
        discoveryTitle?: T;
        discoveryIntro?: T;
        discoveryPoints?:
          | T
          | {
              point?: T;
              id?: T;
            };
        actionLabel?: T;
        actionText?: T;
        impactLabel?: T;
        impactText?: T;
        id?: T;
      };
  audienceSectionTitle?: T;
  audienceItems?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  ctaBannerTitle?: T;
  ctaBannerHighlight?: T;
  ctaBannerTitleSuffix?: T;
  ctaBannerDescription?: T;
  ctaBannerButtonText?: T;
  ctaBannerButtonLink?: T;
  faqSectionTitle?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  deliverablesSectionTitle?: T;
  deliverablesSectionSubtitle?: T;
  deliverables?:
    | T
    | {
        title?: T;
        description?: T;
        whyItExists?: T;
        businessImpact?: T;
        riskMitigation?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    headingPrefix: string;
    headingHighlight: string;
    headingSuffix: string;
    description: string;
    heroImage?: (string | null) | Media;
    primaryButtonText: string;
    primaryButtonLink?: string | null;
    secondaryButtonText: string;
    secondaryButtonLink?: string | null;
  };
  trustedBy: {
    title: string;
    logos?:
      | {
          logo: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  solutions: {
    label: string;
    headingPrefix: string;
    headingHighlight1: string;
    headingMiddle: string;
    headingHighlight2: string;
    cards?:
      | {
          title: string;
          description: string;
          icon?: (string | null) | Media;
          tags?:
            | {
                tag: string;
                id?: string | null;
              }[]
            | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  industries: {
    heading: string;
    description?: string | null;
    items?:
      | {
          name: string;
          description?: string | null;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  process: {
    label: string;
    headingLine1: string;
    headingLine2: string;
    steps?:
      | {
          title: string;
          description: string;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    items?:
      | {
          value: number;
          prefix?: string | null;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  manifesto: {
    label?: string | null;
    text: string;
  };
  testimonials?: {
    label?: string | null;
    heading?: string | null;
    headingHighlight?: string | null;
    headingSuffix?: string | null;
    items?:
      | {
          name: string;
          role: string;
          quote: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    headingLine1?: string | null;
    headingLine2?: string | null;
    headingHighlight?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  footer?: {
    tagline?: string | null;
    newsletterHeading?: string | null;
  };
  footerLinks?: {
    columns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingPrefix?: T;
        headingHighlight?: T;
        headingSuffix?: T;
        description?: T;
        heroImage?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  trustedBy?:
    | T
    | {
        title?: T;
        logos?:
          | T
          | {
              logo?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        label?: T;
        headingPrefix?: T;
        headingHighlight1?: T;
        headingMiddle?: T;
        headingHighlight2?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              tags?:
                | T
                | {
                    tag?: T;
                    id?: T;
                  };
              link?: T;
              id?: T;
            };
      };
  industries?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        label?: T;
        headingLine1?: T;
        headingLine2?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              prefix?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  manifesto?:
    | T
    | {
        label?: T;
        text?: T;
      };
  testimonials?:
    | T
    | {
        label?: T;
        heading?: T;
        headingHighlight?: T;
        headingSuffix?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              quote?: T;
              image?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        headingLine1?: T;
        headingLine2?: T;
        headingHighlight?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        newsletterHeading?: T;
      };
  footerLinks?:
    | T
    | {
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}